#ifndef __MEM_CONFIG_H
#define __MEM_CONFIG_H

/**
 * Ðây là file c?u hình c?a STM32F10x_ExtendLib
 * B?n có th? s?a d?i d?nh nghia macro c?a t?p này d? s?a d?i ho?t d?ng c?a thu vi?n ti?n ích m? r?ng
 *
 * Ý nghia c?a d?u tru?c m?i phuong án nhu sau
 * [>] B?t bu?c/Ði?n vào
 * [-] B?t bu?c ph?i ch?n m?t l?a ch?n, ph?i ch?n m?t m?c trong m?t nhóm
 * [=] B?t bu?c ph?i có nhi?u l?a ch?n, ch?n m?t ho?c nhi?u m?c trong m?t nhóm
 * [+] tùy ch?n
 * */

/**
 * This is the configuration file of STM32F10x_ExtendLib
 * You can modify the macro definition of this file to modify the behavior of the extension library
 *
 * The meaning of the mark before each option is as follows
 * [>] Required/Fill in         
 * [-] Required single choice, one item must be selected within a group
 * [=] Required multiple choice, select one or more items within a group
 * [+] optional 
 * */

/************************************
* ?????? | Memory Manage Config *
************************************/

//Memory size governed by MemoryManage memory management
//If there is no redirection memory management function, then the objects created by the extension library and the memory requested will be included in it.
/*[>]*/ #define MEMORY_MANAGE_POOL_SIZE 8192 /* Bytes */

//The memory block size generated by MemoryManage is the smallest unit of allocated memory.
/*[>]*/ #define MEMORY_MANAGE_BLOCK_SIZE 16 /* bytes */

//The size that MemoryManage appends to the end of the memory block when allocating memory, that is, the extra memory allocated when allocating
/*[>]*/ #define MEMORY_MANAGE_MEMORY_REQUEST_TAIL 0 /* Bytes */

//MemoryManage memory allocation strategy
//Choose one of the following two items
//1. Faster speed, improves the speed of memory application, but may trigger memory defragmentation more frequently, resulting in slower application speed in the future.
//2. Fewer memory fragments, minimizing the probability of memory fragmentation, but it will reduce the speed of application
/*[-] 1 */ #define MEMORY_MANAGE_MEMORY_REQUEST_STRATEGY_FAST_SPEED
/*[-] 2 */ //#define MEMORY_MAMAGE_MEMORY_REQUEST_STRATEGY_LESS_FRAGMENTATION

/************************
 * Debug Mode | Debug Mode *
 *************************/

//debug mode
//Cancel the following comments to make the functions under STM32F10x_ExternLib_Debug effective
//If debugging is completed, you can comment out DEBUG_MODE. After compiling again, the debugging function will be ignored by the compiler.
/*[+]*/ //#define EXTEND_LIB_DEBUG_MODE

//Complete parameter verification
//Declaring EXTEND_LIB_FULL_PARAM_VERIFY can enable parameter verification, and errors can be discovered in time during debugging, but it will reduce operating efficiency.
/*[+]*/ //#define EXTEND_LIB_FULL_PARAM_VERIFY

//Disable parameter validation
//State EXTEND_LIB_NO_PARAM_VERIFY to disable all parameter verification, including necessary verification, which may slightly increase running speed
/*[+]*/ //#define EXTEND_LIB_NO_PARAM_VERIFY

#endif

