#ifndef TEST_LIBRARIES
//==============================================================================================================================================================
#include <soft_spi.h>
#include <config.h>

void SSPI_Write_0(const reg8 Data)
{
  #ifdef SSPI_MSB_0
    SSPI_CONFIG_MOSI_0(!!(Data & BIT7)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT6)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT5)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT4)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT3)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT2)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT1)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT0)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
  #else
    reg8 bit[2] = {0, 0x80};
    SSPI_CONFIG_MOSI_0(!!(Data & BIT0)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT1)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT2)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT3)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT4)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT5)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT6)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT7)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
  #endif
}
reg8 SSPI_WriteRead_0(const reg8 Data)
{
  reg8 rx = 0;
  #ifdef SSPI_MSB_0
    SSPI_CONFIG_MOSI_0(!!(Data & BIT7)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT6)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT5)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT4)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT3)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT2)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT1)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT0)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx <<= 1; rx |= SSPI_READ_MISO_0(); SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
  #else
    reg8 bit[2] = {0, 0x80};
    SSPI_CONFIG_MOSI_0(!!(Data & BIT0)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT1)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT2)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT3)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT4)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT5)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT6)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
    SSPI_CONFIG_MOSI_0(!!(Data & BIT7)); SSPI_CONFIG_SCK_0(!SSPI_POLARITY_0); rx >>= 1; rx |= bit[SSPI_READ_MISO_0()]; SSPI_CONFIG_SCK_0(SSPI_POLARITY_0);
  #endif
  return rx;
}
void SSPI_Writes_0(const unsigned char __gptr* Data, reg8 Length)
{
  while (Length--)
    SSPI_Write_0(*Data++);
}
void SSPI_WriteReads_0(unsigned char* Data, reg8 Length)
{
  while (Length--)
  {
    *Data = SSPI_WriteRead_0(*Data);
    Data++;
  }
}
void SSPI_ReadBytes_0(unsigned char* Buffer, reg8 Length)
{
  while (Length--)
    *Buffer++ = SSPI_WriteRead_0(0xFF);
}
//==============================================================================================================================================================
#endif